export default [
    [
        ["Souris Grise", "Cryptes"],
        ["Moskito",  "Amakna, Astrub, Pandala, Tainéla"],
        ["Arakne",   "Astrub, Pandala, Forêt maléfique"],
        ["Boufton Blanc",    "Amakna, Astrub, Tainéla"],
        ["Boufton Noir", "Amakna, Astrub, Tainéla"],
        ["Tofu Maléfique",   "Cimetière, Crypte, Forêt maléfique"],
        ["Arakne Malade",    "Souterrains d'Astrub"],
        ["Piou Bleu",    "Amakna, Astrub, Bonta, Brâkmar, Sufokia"],
        ["Piou Jaune",   "Amakna, Astrub, Bonta, Brâkmar, Sufokia"],
        ["Piou Rouge",   "Astrub, Bonta, Brâkmar"],
        ["Piou Vert",    "Amakna, Astrub, Bonta, Brâkmar, Sufokia"],
        ["Piou Violet",  "Amakna, Astrub, Bonta, Brâkmar, Sufokia"],
        ["Piou Rose",    "Amakna, Astrub, Bonta, Brâkmar, Sufokia"],
        ["Flammèche Air", "Plaine des Scarafeuilles"],
        ["Flammèche Eau", "Plaine des Scarafeuilles"],
        ["Flammèche Feu", "Plaine des Scarafeuilles"],
        ["Flammèche Terre",   "Plaine des Scarafeuilles"],
        ["Larve Bleue",  "Amakna, Astrub, Pandala"],
        ["Crabe",    "Amakna, Calanques d'Astrub, Rivage sufokien"],
        ["Tofu", "Amakna, Astrub, Tainéla"],
    ],
    [
        ["Tofu Malade",  "Souterrains d'Astrub, Souterrains profonds d'Astrub"],
        ["Champ Champ",  "Amakna, Astrub, Tainéla"],
        ["Pissenlit Diabolique", "Amakna, Astrub, Pâturages de Bonta, Tainéla"],
        ["Arakne Agressive", "Amakna"],
        ["Bandit Manchot",   "Passage vers Brâkmar"],
        ["Rose Démoniaque",  "Amakna, Astrub, Tainéla"],
        ["Gelée Bleue",  "Péninsule des gelées"],
        ["Gelée Menthe", "Péninsule des gelées"],
        ["Kwoan",    "Champ du repos, Cimetière, Forêt maléfique"],
        ["Larve Verte",  "Amakna, Astrub, Pandala"],
        ["Bouftou",  "Amakna, Astrub, Tainéla"],
        ["Kolérat",  "Landes de Sidimote"],
        ["Larve Orange", "Amakna, Astrub, Pandala"],
        ["Boulanger Sombre", "Bordure de Brakmâr, Passage vers Brâkmar, Territoire des Bandits"],
        ["Black Tiwabbit",   "Île de la Cawotte"],
        ["Tiwabbit", "Île de la Cawotte"],
        ["Tiwabbit Kiafin",  "Île de la Cawotte"],
        ["Tournesol Sauvage",    "Amakna, Astrub, Pâturages de Bonta, Tainéla"],
        ["Bandit du clan des Roublards", "Territoire des Bandits"],
        ["Gobelin",  "Campement des Bworks, Campement de Gobelins, Montagne basse des Craqueleurs"],
    ],
    [
        ["Nodkoko",  "Île des naufragés, Plage de la Tortue"],
        ["Tikoko", "Île des naufragés, Plage de la Tortue"],
        ["Trukikol", "Jungle Interdite"],
        ["Sanglier", "Amakna, Forêt d'Astrub"],
        ["Champa Vert",  "Clairière de Brouce Boulgoure"],
        ["Citwouille",   "Forêt maléfique"],
        ["Vampire",  "Cimetière des Torturés, Cryptes"],
        ["Biblop Coco",  "Lac de Cania"],
        ["Biblop Griotte",   "Lac de Cania"],
        ["Biblop Indigo",    "Lac de Cania"],
        ["Biblop Reinette",  "Lac de Cania"],
        ["Chevaucheur de Karne", "Campement des Bworks, Campement de Gobelins, Montagne basse des Craqueleurs"],
        ["Milirat d'Égoutant Malade",    "Souterrains profonds d'Astrub"],
        ["Boo",  "Coin des Boos, Marécages"],
        ["Prespic",  "Amakna, Forêt d'Astrub"],
        ["Cochon de Lait",   "Plaines des Porcass"],
        ["Tortue Jaune", "Plage de la Tortue"],
        ["Wabbit",   "Île des Wabbits"],
        ["Chef de Guerre Bouftou",   "Amakna, Astrub, Tainéla"],
        ["Berger Porkass",   "Plaines des Porcass"],
    ],
    [
        ["Croc Gland",   "Landes de Sidimote"],
        ["Bulbambou",    "Pandala"],
        ["Tortue Bleue", "Plage de la Tortue"],
        ["Tortue Rouge", "Plage de la Tortue"],
        ["Tortue Verte", "Plage de la Tortue"],
        ["Corbac",   "Pénates du Corbac"],
        ["Étoile de la Mer d'Asse",  "Calanques d'Astrub, Rivage sufokien"],
        ["Pichon Blanc", "Calanques d'Astrub, Rivage sufokien"],
        ["Pichon Bleu",  "Calanques d'Astrub, Rivage sufokien"],
        ["Pichon Orange",    "Calanques d'Astrub, Rivage sufokien"],
        ["Pichon Vert",  "Calanques d'Astrub, Rivage sufokien"],
        ["Bambouto", "Pandala"],
        ["Maître Vampire",   "Cimetière des Torturés, Cryptes"],
        ["Minoskito",    "Île du Minotoror"],
        ["Noeul",    "Forêt maléfique"],
        ["Milimulou",    "Amakna, Forêt d'Astrub"],
        ["Fourbasse",    "Jungle Interdite"],
        ["Bulbiflore",   "Pandala"],
        ["Bwork Mage",   "Campement des Bworks, Forêt maléfique"],
        ["Croc Gland Enragé",    "Bordure de Brâkmar"],
    ],
    [
        ["Rose Obscure", "Champs des Ingalsse, Pâturages de Bonta"],
        ["Black Wabbit", "Île des Wabbits"],
        ["Mineur Sombre",    "Bordure de Brakmâr, Passage vers Brâkmar, Territoire des Bandits"],
        ["Bwork Archer", "Campement des Bworks, Forêt maléfique"],
        ["Champa Bleu",  "Clairière de Brouce Boulgoure"],
        ["Champa Marron",    "Clairière de Brouce Boulgoure"],
        ["Champa Rouge", "Clairière de Brouce Boulgoure"],
        ["Craqueboule",  "Montagne basse des Craqueleurs, Montagne des Craqueleurs"],
        ["Mandrine", "Île du Minotoror"],
        ["Kitsou Nakwa", "Pandala"],
        ["Gargrouille",  "Champ du repos"],
        ["Dragodinde Amande Sauvage",    "Territoire des Dragodindes Sauvages"],
        ["Gelée Fraise", "Péninsule des gelées"],
        ["Wabbit Squelette", "Îlot des Tombeaux"],
        ["Chafer Invisible", "Bois de Litneg, Cimetière, Cimetière des Torturés, Forêt maléfique"],
        ["Craqueleur",   "Montagne basse des Craqueleurs, Montagne des Craqueleurs"],
        ["Bwork",    "Campement des Bworks, Forêt maléfique"],
        ["Abraknyde",    "Orée de la forêt des Abraknydes"],
        ["Kraméléhon",   "Île du Minotoror"],
    ],
    [
        ["Scarafeuille Blanc",   "Plaine des Scarafeuilles"],
        ["Scarafeuille Bleu",    "Plaine des Scarafeuilles"],
        ["Scarafeuille Rouge",   "Plaine des Scarafeuilles"],
        ["Scarafeuille Vert",    "Plaine des Scarafeuilles"],
        ["Rib",  "Bois de Litneg, Cimetière, Forêt maléfique"],
        ["Blop Coco",    "Lac de Cania"],
        ["Blop Griotte", "Lac de Cania"],
        ["Blop Indigo",  "Lac de Cania"],
        ["Blop Reinette",    "Lac de Cania"],
        ["Cochon de Farle",  "Labyrinthe du Dragon Cochon, Territoire des Porcos"],
        ["Scaratos", "Labyrinthe du Minotoror"],
        ["Boomba",   "Chemin du Crâne"],
        ["Tronknyde",    "Orée de la forêt des Abraknydes"],
        ["Chafer Fantassin", "Bois de Litneg, Cimetière"],
        ["Pichon Kloune",    "Rivage sufokien"],
        ["Abrakne",  "Orée de la forêt des Abraknydes"],
        ["Chafer",   "Bois de Litneg, Cimetière, Cimetière des Torturés, Forêt maléfique"],
        ["Crocodaille",  "Marécages"],
        ["Rat d'Égoutant Malade",    "Souterrains du Château d'Amakna"],
        ["Scorbute", "Landes de Sidimote"],
    ],
    [
        ["Dragodinde Rousse Sauvage",    "Territoire des Dragodindes Sauvages"],
        ["Forgeron Sombre",  "Bordure de Brakmâr, Passage vers Brâkmar, Territoire des Bandits"],
        ["Crustorail Kouraçao",  "Plage de Corail"],
        ["Crustorail Malibout",  "Plage de Corail"],
        ["Crustorail Morito",    "Plage de Corail"],
        ["Crustorail Passaoh",   "Plage de Corail"],
        ["Bulbuisson",   "Pandala"],
        ["Arakne Majeure",   "Égouts de Bonta et Brâkmar, Forêt maléfique, Marécages, Orée de la forêt des Abraknydes"],
        ["Araknawa", "Pandala"],
        ["Grand Pa Wabbit",  "Île des Wabbits"],
        ["Wo Wabbit",    "Île des Wabbits"],
        ["Cavalier Porkass", "Plaine des Porkass"],
        ["Aboub",    "Territoire des Dopeuls"],
        ["Amlub",    "Baie de Cania, Territoire des Dopeuls"],
        ["Codem",    "Baie de Cania, Territoire des Dopeuls"],
        ["Gink", "Territoire des Dopeuls"],
        ["Kirevam",  "Baie de Cania, Territoire des Dopeuls"],
        ["Let Emoliug",  "Baie de Cania, Territoire des Dopeuls"],
        ["Nebgib",   "Territoire des Dopeuls"],
        ["Nipul",    "Territoire des Dopeuls"],
    ],
    [
        ["Osurc",    "Territoire des Dopeuls"],
        ["Susej",    "Baie de Cania, Territoire des Dopeuls"],
        ["Kokoko",   "Île des naufragés, Plage de la Tortue"],
        ["Chafer Archer",    "Bois de Litneg, Cimetière des Héros, Cimetière des Torturés, Forêt maléfique"],
        ["Chafer Lancier",   "Bois de Litneg, Cimetière des Héros, Cimetière des Torturés"],
        ["Dok Alako",    "Montagne des Koalaks"],
        ["Koalak Immature",  "Montagne des Koalaks"],
        ["Gamino",   "Labyrinthe du Minotoror"],
        ["Chamane d'Égoutant",    "Égouts de Bonta et Brâkmar, Souterrains du Château d'Amakna"],
        ["Le Ouassingue Entourbé",   "Tourbière nauséabonde, Tourbière sans fond"],
        ["La Ouassingue",    "Champ du repos"],
        ["Le Ouassingue",    "Champ du repos"],
        ["Palmifleur Malibout",  "Plage de Corail"],
        ["Palmifleur Morito",    "Plage de Corail"],
        ["Palmifleur Passaoh",   "Plage de Corail"],
        ["Sanglier des Plaines", "Plaine des Porkass"],
        ["Abraknyde Vénérable",  "Forêt Sombre"],
        ["Craqueleur des Plaines",   "Plaines Rocheuses"],
        ["Pandit",   "Pandala"],
        ["Chafer d'Élite",   "Cimetière des Héros, Cimetière des Torturés"],
    ],
    [
        ["Maître Bolet", "Route de Brâkmar, Routes Rocailleuses"],
        ["Craqueboule Poli", "Plaines herbeuses"],
        ["Pandikaze",    "Pandala Air"],
        ["Kanniboul Ark", "Forêt des Masques"],
        ["Kanniboul Jav",    "Forêt des Masques"],
        ["Kanniboul Sarbak", "Forêt des Masques"],
        ["Kanniboul Eth",    "Forêt des Masques"],
        ["Pandalette Ivre",  "Bordure de Terrdala"],
        ["Rat d'Égoutant",   "Égouts de Bonta et Brâkmar, Souterrains du Château d'Amakna"],
        ["Palmifleur Kouraçao",  "Plage de Corail"],
        ["Ouginak",  "Landes de Sidimote"],
        ["DragOeuf Blanc Immature",  "Presqu'île des Dragoeufs"],
        ["DragOeuf Doré Immature",   "Presqu'île des Dragoeufs"],
        ["DragOeuf Noir Immature",   "Presqu'île des Dragoeufs"],
        ["DragOeuf de Saphir Immature",  "Presqu'île des Dragoeufs"],
        ["Dragoss Blanc",    "Sanctuaire des Dragoeufs"],
        ["Dragoss Doré", "Sanctuaire des Dragoeufs"],
        ["Dragoss Noir", "Sanctuaire des Dragoeufs"],
        ["Dragoss de Saphir",    "Sanctuaire des Dragoeufs"],
        ["Léopardo", "Pandala Feu"],
    ],
    [
        ["Serpiplume",   "Île du Minotoror"],
        ["Corailleur",   "Plage de Corail"],
        ["Kitsou Nae",   "Pandala"],
        ["Raul Mops",    "Rivage sufokien"],
        ["Pandawa Ivre", "Bordure de Terrdala"],
        ["Cooleuvre",    "Pandala Neutre"],
        ["Coquille Explosive",   "Sousterrain des Dragoeufs, Village des Dragoeufs"],
        ["Canondorf",   "Chemin du Crâne"],
        ["Nakunbra", "Chemin du Crâne"],
        ["Don Duss Ang", "Labyrinthe du Dragon Cochon"],
        ["DragOeuf Blanc",   "Presqu'île des Dragoeufs"],
        ["DragOeuf Doré",    "Presqu'île des Dragoeufs"],
        ["DragOeuf Noir",    "Presqu'île des Dragoeufs"],
        ["DragOeuf de Saphir",   "Presqu'île des Dragoeufs"],
        ["Koalak Coco",  "Canyon sauvage"],
        ["Koalak Griotte",   "Canyon sauvage"],
        ["Koalak Indigo",    "Canyon sauvage"],
        ["Koalak Reinette",  "Canyon sauvage"],
        ["Rat d'Hyoactif",   "Égouts de Bonta et Brâkmar"],
        ["Sparo",    "Arche d'Otomaï"],
    ],
    [
        ["Chiendent",    "Jungle obscure"],
        ["Fantôme Apero",    "Cimetière des Torturés"],
        ["Fantôme Ardent",   "Cimetière des Torturés"],
        ["Fantôme Arepo",    "Cimetière des Torturés"],
        ["Fantôme Brave",    "Cimetière des Torturés"],
        ["Don Dorgan",   "Labyrinthe du Dragon Cochon"],
        ["Barbroussa",   "Arche d'Otomaï"],
        ["Le Flib",  "Arche d'Otomaï"],
        ["Nerbe",    "Jungle obscure"],
        ["Chef Crocodaille",  "Marécage, Marécages sans fond"],
        ["Serpentin",    "Champs de Cania"],
        ["Kanigrou", "Routes de Brâkmar, Routes Rocailleuses"],
        ["Bitouf des Plaines",   "Plaines herbeuses"],
        ["Craqueleur Poli",  "Plaines herbeuses"],
        ["Mufafah",  "Plaines herbeuses"],
        ["Mulou",    "Route de Brâkmar"],
        ["Pandule",  "Pandala"],
        ["Kido", "Plaines herbeuses"],
        ["Kilibriss",    "Plaines herbeuses"],
        ["DragOeuf Blanc Éveillé",   "Presqu'île des Dragoeufs"],
    ],
    [
        ["DragOeuf Doré Éveillé",    "Presqu'île des Dragoeufs"],
        ["DragOeuf Noir Éveillé",    "Presqu'île des Dragoeufs"],
        ["DragOeuf de Saphir Éveillé",   "Presqu'île des Dragoeufs"],
        ["Dragueuse",    "Sanctuaire des Dragoeufs"],
        ["Guerrier Koalak",  "Vallée de la Morh'Kitu"],
        ["Braconnier",   "Pandala Neutre"],
        ["Oni",  "Forêt maléfique"],
        ["Warko Marron", "Canyon sauvage, Forêt de Kaliptus"],
        ["Kitsou Nere",  "Pandala"],
        ["Abraknyde Sombre", "Forêt Sombre"],
        ["Bulbig",   "Pandala"],
        ["Fossoyeur Koalak", "Cimetière primitif"],
        ["Koalak Forestier", "Forêt de Kaliptus"],
        ["Piralak",  "Lacs enchantés"],
        ["Pékeualak",    "Lacs enchantés"],
        ["Gloutovore",   "Jungle Interdite"],
        ["Abrakne Sombre",   "Forêt Sombre"],
        ["Dragodinde Dorée Sauvage", "Territoire des Dragodindes Sauvages"],
        ["Chevaucheur Koalak",   "Cimetière primitif"],
        ["Meupette", "Tronc de l'arbre Hakam"],
    ],
    [
        ["Bambouto Sacré",   "Pandala Neutre"],
        ["Dragoeuf Guerrier",    "Sanctuaire des Dragoeufs"],
        ["Dragoeuf Volant",  "Sanctuaire des Dragoeufs"],
        ["Aerohouctor le Guerrier",  "Souterrains des Dragoeufs"],
        ["Aquabralak le Guerrier",   "Souterrains des Dragoeufs"],
        ["Ignelicrobur le Guerrier", "Souterrains des Dragoeufs"],
        ["Terrakoubiak le Guerrier", "Souterrains des Dragoeufs"],
        ["Disciple Zoth",    "Village de la Canopée"],
        ["Brouture", "Jungle obscure"],
        ["Koalak Sanguin",   "Vallée de la Morh'Kitu"],
        ["Bitouf Sombre",    "Jungle obscure"],
        ["Floribonde",   "Jungle obscure"],
        ["Fécorce",  "Jungle obscure"],
        ["Koalak Farouche",  "Vallée de la Morh'Kitu"],
        ["Mama Koalak",  "Canyon sauvage"],
        ["Momie Koalak", "Cimetière primitif"],
        ["Bourbassingue",    "Tourbière nauséabonde, Tourbière sans fond"],
        ["Warko Violet", "Vallée de la Morh'Kitu"],
        ["Gamine Zoth",  "Village de la Canopée"],
        ["Guerrier Zoth",    "Village de la Canopée"],
    ],
    [
        ["Tourbassingue",    "Tourbière nauséabonde, Tourbière sans fond"],
        ["Abrakleur Sombre", "Jungle obscure"],
        ["Dragoss Blanc Éveilé", "Sanctuaire des Dragoeufs"],
        ["Dragoss Doré Éveillé", "Sanctuaire des Dragoeufs"],
        ["Dragoss Noir Éveillé", "Sanctuaire des Dragoeufs"],
        ["Dragoss de Saphir Éveillé",    "Sanctuaire des Dragoeufs"],
        ["Soryo Firefoux",   "Pandala Feu"],
        ["Kitsou Nufeu", "Pandala"],
        ["Maho Firefoux",    "Pandala Feu"],
        ["Drakoalak",    "Canyon sauvage"],
        ["Fauchalak",    "Vallée de la Morh'Kitu"],
        ["Maître Koalak",    "Cimetière primitif"],
        ["Poolay",   "Feuillage de l'arbre Hakam, Tronc de l'arbre Hakam"],
        ["Ignerkocropos l'Affamé",   "Sanctuaire des Dragoeufs"],
        ["Terraburkal le Perfide",   "Sanctuaire des Dragoeufs"],
        ["Aqualikros l'Impitoyable", "Sanctuaire des Dragoeufs"],
        ["Aerotrugobur le Malveillant",  "Sanctuaire des Dragoeufs"],
        ["Troollaraj",   "Bois de Litneg"],
    ],
    [
        ["Sergent Zoth", "Village de la Canopée"],
        ["Maître Zoth",  "Village de la Canopée"],
        ["Kaskargo",    "Feuillage de l'arbre Hakam, Tronc de l'arbre Hakam"],
        ["Bitouf Aérien",    "Feuillage de l'arbre Hakam, Tronc de l'arbre Hakam"],
        ["Abrakleur Clair",  "Tronc de l'arbre Hakam"],
        ["Yokai Firefoux",   "Pandala Feu"],
        ["Champaknyde",  "Caverne des Fungus"],
        ["Tromperelle",  "Caverne des Fungus"],
        ["Champodonte",  "Caverne des Fungus"],
        ["Champbis", "Caverne des Fungus"],
        ["Champ à gnon", "Caverne des Fungus"],
        ["Champmane",    "Caverne des Fungus"],
        ["Fantôme Léopardo", "Île de Grobe"],
        ["Fantôme Pandikaze",    "Île de Grobe"],
        ["Fantôme Pandule",  "Île de Grobe"],
        ["Fantôme Soryo Firefoux",    "Île de Grobe"],
        ["Pandore",  "Pandala"],
        ["Roissingue",   "Tourbière nauséabonde, Tourbière sans fond"],
        ["Fantôme Maho Firefoux", "Île de Grobe"],
        ["Fantôme Yokai Firefoux",    "Île de Grobe"],
    ],
    [
        ["Fantôme Pandore",  "Île de Grobe"],
        ["Fantôme Tanukouï San", "Île de Grobe"]
    ],
    [
        ["Mob l'Éponge",    "Donjon Ensablé"],
        ["Bouftou Royal",   "Donjon des Bouftous"],
        ["Tournesol Affamé",    "Donjon des Champs"],
        ["Gelée Royale Bleue",  "Gelaxième dimension"],
        ["Gelée Royale Menthe", "Gelaxième dimension"],
        ["Shin Larve",  "Donjon des Larves"],
        ["Wabbit GM",   "Souterrains des Wabbits"],
        ["Scarabosse Doré", "Donjon des Scarafeuilles"],
        ["Bworkette",   "Donjon des Bworks"],
        ["Dragon Cochon",   "Antre du Dragon Cochon"],
        ["Mominotor",   "Labyrinthe du Minotoror, Centre du labyrinthe du Minotoror"],
        ["Déminoboule", "Labyrinthe du Minotoror, Centre du labyrinthe du Minotoror"],
        ["Tofu Royal",  "Tofulailler Royal"],
        ["Blop Coco Royal", "Clos des Blops, Antre du Blop Multicolore Royal"],
        ["Blop Griotte Royal",  "Clos des Blops, Antre du Blop Multicolore Royal"],
        ["Blop Indigo Royal",   "Clos des Blops, Antre du Blop Multicolore Royal"],
        ["Blop Reinette Royal", "Clos des Blops, Antre du Blop Multicolore Royal"],
        ["Rat Noir",    "Donjon des Rats de Brâkmar, Donjon des Rats du Château d'Amakna"],
        ["Rat Blanc",   "Donjon des Rats de Bonta, Donjon des Rats du Château d'Amakna"],
        ["Minotoror",   "Centre du labyrinthe du Minotoror"],
    ],
    [
        ["Hell Mina",   "Forêt maléfique"],
        ["Tanukouï San",    "Donjon des Kitsounes"],
        ["Craqueleur Légendaire",   "Pitons Rocheux des Craqueleurs"],
        ["Gardienne des Égouts",    "Égouts de Bonta et Brâkmar"],
        ["Gelée Royale Fraise", "Gelaxième dimension"],
        ["Maître Corbac",   "Bibliothèque du Maître Corbac"],
        ["Blop Multicolore Royal",  "Antre du Blop Multicolore Royal"],
        ["Corailleur Magistral",    "Grotte Hesque"],
        ["Gourlo le Terrible",  "Cale de l'arche d'Otomaï"],
        ["Meulou",  "Donjon des Canidés"],
        ["Wa Wabbit",   "Château du Wa Wabbit"],
        ["Moon",    "Arbre de Moon"],
        ["Koulosse",    "Caverne du Koulosse"],
        ["Skeunk",  "Repaire de Skeunk"],
        ["Abraknyde Ancestral", "Domaine Ancestral"],
        ["Maître Pandore",  "Repaire des Pandikazes"],
        ["Tynrils (Ahuri, Consterné, Déconcerté, Perfide)", "Laboratoire du Tynril"],
    ],
    [
        ["Gelée Royale Citron", "Gelaxième dimension"],
        ["Touchparak",  "Donjon des Firefoux"],
        ["Bworker", "Donjon du Bworker"],
        ["Sphincter Cell",  "Donjon des Rats du Château d'Amakna"],
        ["Minotot", "Centre du labyrinthe du Minotoror"],
        ["Silf le Rasboul Majeur",  "Goulet du Rasboul"],
        ["Crocabulia",  "Donjon des Dragoeufs"],
        ["Péki Péki",   "Donjon des Firefoux"],
        ["Chêne Mou",   "Clairière du Chêne Mou"],
        ["Ougah",   "Donjon Fungus"],
        ["Kimbo",   "Canopée du Kimbo"],
    ],
    [
        ["Sourizoto le Collant","Souris Grise"],
        ["Mosketère le Dévoué","Moskito"],
        ["Arakule la Revancharde","Arakne"],
        ["Boudalf le Blanc","Boufton Blanc"],
        ["Boulgourvil le Lointain","Boufton Noir"],
        ["Tofumanchou l'Empereur","Tofu Maléfique"],
        ["Arachitik la Souffreteuse","Arakne Malade"],
        ["Pioustone le Problème","Piou Bleu"],
        ["Pioulbrineur le Mercenaire","Piou Jaune"],
        ["Pioulette la Coquine","Piou Rouge"],
        ["Pioukas la Plante","Piou Vert"],
        ["Pioussokrim le Délétère","Piou Violet"],
        ["Craraboss le Féérique","Crabe"],
        ["Larvonika l'Instrument","Larve Bleue"],
        ["Pioufe la Maquillée","Piou Rose"],
        ["Tofuldebeu l'Explosif","Tofu"],
        ["Tofurapin le Pétri","Tofu Malade"],
        ["Chamchie le Difficile","Champ Champ"],
        ["Pissdane l'Insipide","Pissenlit Diabolique"],
        ["Araknay la Galopante","Arakne Agressive"],
    ],
    [
        ["Bandapar l'Exclu","Bandit Manchot"],
        ["Roz la Magicienne","Rose Démoniaque"],
        ["Gelanal le Huileux","Gelée Bleue"],
        ["Kwoanneur le Frimeur","Kwoan"],
        ["Larchimaide la Poussée","Larve Verte"],
        ["Boufdégou le Refoulant","Bouftou"],
        ["Kolforthe l'Indécollable","Kolérat"],
        ["Geloliaine l'Aérien","Gelée Menthe"],
        ["Larvapstrè le Subjectif","Larve Orange"],
        ["Serpistol l'Illustre","Serpentin"],
        ["Tiwa'Missou le Gateux","Black Tiwabbit"],
        ["Boudur le Raide","Boulanger Sombre"],
        ["Tiwalpé le Dévêtu","Tiwabbit"],
        ["Tiwoflan le Lâche","Tiwabbit Kiafin"],
        ["Tour le Vice","Tournesol Sauvage"],
        ["Bandson le Tonitruant","Bandit du clan des Roublards"],
        ["Gobstiniais le Têtu","Gobelin"],
        ["Nodkoku le Trahi","Nodkoko"],
        ["Tikosto le Mousse","Tikoko"],
        ["Trukul le Lent","Trukikol"],
    ],
    [
        ["Sangria le Fruité","Sanglier"],
        ["Champayr le Disjoncté","Champa Vert"],
        ["Citassaté le Service","Citwouille"],
        ["Vampunor le Glacial","Vampire"],
        ["Bilvoezé le Bonimenteur","Biblop Coco"],
        ["Bi le Partageur","Biblop Griotte"],
        ["Bistou le Quêteur","Biblop Indigo"],
        ["Bistou le Rieur","Biblop Reinette"],
        ["Chevaustine le Reconstruit","Chevaucheur de Karne"],
        ["Milipussien le Géant","Milirat d'Égoutant Malade"],
        ["Boostif l'Affamé","Boo"],
        ["Preskapwal le Tendancieux","Prespic"],
        ["Chonstip la Passagère","Cochon de Lait"],
        ["Torthur la Lutte","Tortue Jaune"],
        ["Wabbitud le Constant","Wabbit"],
        ["Porfavor le Quémandeur","Berger Porkass"],
        ["Bulleur le Dormeur","Bulbambou"],
        ["Bouflet le Puéril","Chef de Guerre Bouftou"],
        ["Cromikay le Néophyte","Croc Gland"],
        ["Tortenssia la Fleurie","Tortue Bleue"],
    ],
    [
        ["Bambouské le Camouflé","Bambouto"],
        ["Corpat le Vampire","Corbac"],
        ["Pichduitre le Totem","Pichon Blanc"],
        ["Pichdourse le Puissant","Pichon Bleu"],
        ["Pichtoire l'Érudit","Pichon Orange"],
        ["Pichakoté le Dégoutant","Pichon Vert"],
        ["Tortorak le Cornu","Tortue Rouge"],
        ["Maître Amboat le Moqueur","Maître Vampire"],
        ["Buldeflore le Pénétrant","Bulbiflore"],
        ["Fourapin le Chaud","Fourbasse"],
        ["Milipatte la Griffe","Milimulou"],
        ["Minoskour le Sauveur","Minoskito"],
        ["Neufedur le Flottant","Noeul"],
        ["Tortilleur le Coulé","Tortue Verte"],
        ["Bwormage le Respectueux","Bwork Mage"],
        ["Wagnagnah le Sanglant","Black Wabbit"],
        ["Crognan le Barbare","Croc Gland Enragé"],
        ["Rostensyl la Cuisinière","Rose Obscure"],
        ["Minsinistre l'Élu","Mineur Sombre"],
        ["Barchwork le Multicolore","Bwork Archer"],
    ],
    [
        ["Champayt l'Odorant","Champa Bleu"],
        ["Chamflay le Ballonné","Champa Marron"],
        ["Chamdblé le Cultivé","Champa Rouge"],
        ["Craquetuss le Piquant","Craqueboule"],
        ["Mandalo l'Aqueuse","Mandrine"],
        ["Kitsoupierre le Récipient","Kitsou Nakwa"],
        ["Garsim le Mort","Gargrouille"],
        ["Draglida la Disparue","Dragodinde Amande Sauvage"],
        ["Gelaviv le Glaçon","Gelée Rouge"],
        ["Watdogue le Bien Nommé","Wabbit Squelette"],
        ["Chafalfer l'Optimiste","Chafer Invisible"],
        ["Crakmitaine le Faucheur","Craqueleur"],
        ["Bworkasse le Dégoutant","Bwork"],
        ["Abrakroc l'Édenté","Abraknyde"],
        ["Krapahut le Randonneur","Kraméléhon"],
        ["Scapé l'Épée","Scarafeuille Blanc"],
        ["Scarfayss le Balafré","Scarafeuille Bleu"],
        ["Scarouarze l'Épopée","Scarafeuille Rouge"],
        ["Scaramel le Fondant","Scarafeuille Vert"],
        ["Ribibi le Cher","Rib"],
    ],
    [
        ["Blorie l'Assourdissante","Blop Coco"],
        ["Blordur l'Infect","Blop Griotte"],
        ["Bloporte le Veule","Blop Indigo"],
        ["Blof l'Apathique","Blop Reinette"],
        ["Boombata le Garde","Boomba"],
        ["Farlon l'Enfant","Cochon de Farle"],
        ["Scaratyn l'Huître","Scaratos"],
        ["Chaffoin le Sournois","Chafer Fantassin"],
        ["Picht le Brioché","Pichon Kloune"],
        ["Tronkoneuz la Tranchante","Tronknyde"],
        ["Abrakadnuzar","Abrakne"],
        ["Chafemal le Bagarreur","Chafer"],
        ["Crolnareff l'Exilé","Crocodaille"],
        ["Radoutable le Craint","Rat d'Égoutant Malade"],
        ["Scorpitène l'Enflammé","Scorbute"],
        ["Dragnoute l'Irascible","Dragodinde Rousse Sauvage"],
        ["Bulsavon le Gonflé","Bulbuisson"],
        ["Crustterus l'Organique","Crustorail Kouraçao"],
        ["Crustensyl le Pragmatique","Crustorail Malibout"],
        ["Cruskof le Rustre","Crustorail Morito"],
    ],
    [
        ["Crusmeyer le Pervers","Crustorail Passaoh"],
        ["Forboyar l'Énigmatique","Forgeron Sombre"],
        ["Arakozette l'Intrépide","Araknawa"],
        ["Arabord la Cruche","Arakne Majeure"],
        ["Grandilok le Clameur","Grand Pa Wabbit"],
        ["Wokènrôl le Danseur","Wo Wabbit"],
        ["Cavordemal le Sorcier","Cavalier Porkass"],
        ["Aboudbra le Porteur","Aboub"],
        ["Ameur la Laide","Amlub"],
        ["Codenlgaz le Problème","Codem"],
        ["Ginsenk le Stimulant","Gink"],
        ["Kiroyal le Sirupeux","Kirevam"],
        ["Let le Rond","Let Emoliug"],
        ["Nelvin le Boulet","Nedgib"],
        ["Nipulnislip l'Exhibitionniste","Nipul"],
        ["Osuxion le Vampirique","Osurc"],
        ["Susbewl l'Hypocrite","Susej"],
        ["Koktèle le Secoué","Kokoko"],
        ["Chafmarcel le Fêtard","Chafer Archer"],
        ["Chalan le Commerçant","Chafer Lancier"],
    ],
    [
        ["Chamitant le Dilettante","Chamane d'Égoutant"],
        ["Doktopuss le Maléfique","Dok Alako"],
        ["Germinol l'Indigent","Gamino"],
        ["Koalastrof la Naturelle","Koalak Immature"],
        ["Ouature la Mobile","La Ouassingue"],
        ["Ouassébo l'Esthète","Le Ouassingue"],
        ["Ouashouash l'Exubérant","Le Ouassingue Entourbé"],
        ["Palmito le Menteur","Palmifleur Malibout"],
        ["Palmiche le Serein","Palmifleur Morito"],
        ["Palmiflette le Convivial","Palmifleur Passaoh"],
        ["Sampi l'Éternel","Sanglier des Plaines"],
        ["Abrakildas le Vénérable","Abraknyde Vénérable"],
        ["Cramikaz le Suicidaire","Craqueleur des Plaines"],
        ["Pandimaensh l'Animateur","Pandit"],
        ["Chafrit le Barbare","Chafer d'Élite"],
        ["Craquetou le Fissuré","Craqueboule Poli"],
        ["Maître Onom le Régulier","Maître Bolet"],
        ["Pandimy le Contagieux","Pandikaze"],
        ["Kannibal le Lecteur","Kanniboul Ark"],
        ["Kapota la Fraise","Kanniboul Jav"],
    ],
    [
        ["Kannémik le Maigre","Kanniboul Sarbak"],
        ["Kannisterik le Forcené","Kanniboul Eth"],
        ["Pandanlagl la Saoule","Pandalette Ivre"],
        ["Palmbytch la Bronzée","Palmifleur Kouraçao"],
        ["Ratlbol l'Aigri","Rat d'Égoutant"],
        ["Ougaould le Parasite","Ouginak"],
        ["Corboyard l'Énigmatique","Corailleur"],
        ["Dragstik le Frustre","DragOeuf Blanc Immature"],
        ["Dragtula l'Ancien","DragOeuf de Saphir Immature"],
        ["Dragsta le Détendu","DragOeuf Noir Immature"],
        ["Dragstore le Généraliste","DragOeuf Doré Immature"],
        ["Dragtopaile l'Excavateur","Dragoss Blanc"],
        ["Dragioli le Succulent","Dragoss de Saphir"],
        ["Dragalgan l'Effervescent","Dragoss Doré"],
        ["Dragybuss le Sucré","Dragoss Noir"],
        ["Léopolnor le Barde","Léopardo"],
        ["Serpistule le Purulent","Serpiplume"],
        ["Kitsoudbra le Malodorant","Kitsou Nae"],
        ["Pandouille le Titubant","Pandawa Ivre"],
        ["Rauligo le Sale","Raul Mops"],
    ],
    [
        ["Cooligane le Nevrosé","Cooleuvre"],
        ["Caboume l'Artilleur","Canondorf"],
        ["Nakuneuye le Borgne","Nakunbra"],
        ["Dragstayr le Fonceur","DragoOeuf Blanc"],
        ["Dragmoclaiss le Fataliste","DragOeuf de Saphir"],
        ["Dragkouine la Déguisée","DragOeuf Doré"],
        ["Dragnostik le Sceptique","DragOeuf Noir"],
        ["Koamaembair le Coulant","Koalak Coco"],
        ["Koakofrui le Confit","Koalak Griotte"],
        ["Koaskette la Chapelière","Koalak Indigo"],
        ["Koarmit la Batracienne","Koalak Reinette"],
        ["Ratéhaifaim le Professeur","Rat d'Hyoactif"],
        ["Sparoket le Lanceur","Sparo"],
        ["Chiendanlémin l'Illusionniste","Chiendent"],
        ["Fanlabiz le Véloce","Fantôme Apero"],
        ["Fandanleuil le Précis","Fantôme Ardent"],
        ["Fantoch le Pantin","Fantôme Arepo"],
        ["Fantrask le Rêveur","Fantôme Brave"],
        ["Barebourd le Comte","Barbroussa"],
        ["Nerdeubeu le Flagellant","Nerbe"],
    ],
    [
        ["Crathdogue le Cruel","Craqueleur Poli"],
        ["Toufou le Benêt","Bitouf des Plaines"],
        ["Crok le Beau"," Chef Crocodaille"],
        ["Fanfancisco le Cosmopolite","Fantôme Tanuki Chan (Air)"],
        ["Fanjipann le Sucré","Fantôme Tanuki Chan (Eau)"],
        ["Fanhnatur le Simple","Fantôme Tanuki Chan (Terre)"],
        ["Fanjo le Pilote","Fantôme Tanuki Chan (Feu)"],
        ["Fanlmyl l'Acuité","Fantôme Tanuki Chan (Neutre)"],
        ["Kanasukr le Mielleux","Kanigrou"],
        ["Mufguedin le Suprême","Mufafah"],
        ["Muloufok l'Hilarant","Mulou"],
        ["Pangraive le Militant","Pandule"],
        ["Kido l'Âtre","Kido"],
        ["Kilimanj'haro le Grimpeur","Kilibriss"],
        ["Dragoo le Cramoisi","DragOeuf Blanc Éveillé"],
        ["Dragtonien le Malvoyant","DragOeuf de Saphir Éveillé"],
        ["Dragma le Bouillant","DragOeuf Doré Éveillé"],
        ["Dragoeth le Penseur","DragOeuf Noir Éveillé"],
        ["Dragonienne l'Économe","Dragueuse"],
        ["Guerrite le Veilleur","Guerrier Koalak"],
    ],
    [
        ["Bramin le Bicéphale","Braconnier"],
        ["Onihylis le Destructeur","Oni"],
        ["Warkolad l'Étreinte","Warko Marron"],
        ["Kitsoupopulère le Généreux","Kitsou Nere"],
        ["Abrakanette l'Encapsulé","Abraknyde Sombre"],
        ["Bulgig le Danseur","Bulbig"],
        ["Fossamoel le Juteux","Fossoyeur Koalak"],
        ["Gloubibou le Gars","Gloutovore"],
        ["Koasossyal le Psychopathe","Koalak Forestier"],
        ["Pékeutar le Tireur","Pékeualak"],
        ["Piradain le Pingre","Piralak"],
        ["Abraklette le Fondant","Abrakne Sombre"],
        ["Koamag'oel le Défiguré","Chevaucheur Koalak"],
        ["Meuroup le Prêtre","Meupette"],
        ["Bambono le Divin","Bambouto Sacré"],
        ["Dragdikal le Décisif","Dragoeuf Guerrier"],
        ["Dragobert le Monarque","Dragoeuf Volant"],
        ["Diskord le Belliqueux","Disciple Zoth"],
        ["Brouste l'Humiliant","Brouture"],
        ["Bitoven le Musicien","Bitouf Sombre"],
    ],
    [
        ["Ecorfé la Vive","Fécorce"],
        ["Floanna la Blonde","Floribonde"],
        ["Koalvissie le Chauve","Koalak Sanguin"],
        ["Koalaboi le Calorifère","Koalak Farouche"],
        ["Mamakomou l'Âge","Mama Koalak"],
        ["Momikonos la Bandelette","Momie Koalak"],
        ["Bouliver le Géant","Bourbassingue"],
        ["Wara l'Amer","Warko Violet"],
        ["Gastroth la Contagieuse","Gamine Zoth"],
        ["Guerumoth le Collant","Guerrier Zoth"],
        ["Tourbiket le Virevoletant","Tourbassingue"],
        ["Abrakine le Sombre","Abrakleur Sombre"],
        ["Dragminster le Magicien","Dragoss Blanc Éveillé"],
        ["Dragtarus le Bellâtre","Dragoss Doré Éveillé"],
        ["Draquetteur le Voleur","Dragoss Noir Éveillé"],
        ["Drageaufol la Joyeuse","Dragoss de Saphir Éveillé"],
        ["Soryonara le Poli","Soryo Firefoux"],
        ["Kitsoufre l'Explosif","Kitsou Nufeu"],
        ["Drakolage le Tentateur","Drakoalak"],
        ["Faufoll la Joyeuse","Fauchalak"],
    ],
    [
        ["Mahoku le Botté","Maho Firefoux"],
        ["Maître Koantik le Théoricien","Maître Koalak"],
        ["Poolopo la Traditionnelle","Poolay"],
        ["Trooyé l'Oxydé","Troollaraj"],
        ["Seripoth l'Ennemi","Sergent Zoth"],
        ["Kaskapointhe la Couverte","Kaskargo"],
        ["Toutouf le Velu","Bitouf Aérien"],
        ["Abrinos le Clair","Abrakleur Clair"],
        ["Don Kizoth l'Obstiné","Maître Zoth"],
        ["Chamilero le Malchanceux","Champaknyde"],
        ["YokaiKoral le Duel","Yokai Firefoux"],
        ["Tromplamor le Survivant","Tromperelle"],
        ["Chamoute le Duveteux","Champodonte"],
        ["Fansissla l'Âne","Fantôme Léopardo"],
        ["Fanstatik l'Étonnant","Fantôme Pandikaze"],
        ["Champoul l'Illuminé","Champbis"],
        ["Champolyon le Polyglotte","Champ à Gnons"],
        ["Champmé le Méchant","Champmane"],
        ["Fandouich l'Hautain","Fantôme Pandule"],
        ["Fanhopruno le Gourmet","Fantôme Soryo Firefoux"],
    ],
    [
        ["Pandive le Végétarien","Pandore"],
        ["Roy le Merlin","Roissingue"],
        ["Fanlagoel le Comique","Fantôme Maho Firefoux"],
        ["Fantassein le Soldat","Fantôme Yokai Firefoux"],
        ["Fanburn le Viril","Fantôme Tanukouï San"],
        ["Fansiss la Brêle","Fantôme Pandore"],
    ],
    [
        ["Kralamoure Géant", "Antre du Kralamoure Géant"]
    ]
];