export default [
    [
        ["Souris Grise", "Cryptes"],
        ["Moskito",  "Amakna, Astrub, Pandala"],
        ["Arakne",   "Amakna, Astrub, Pandala"],
        ["Boufton Blanc",    "Amakna, Astrub, Tainéla"],
        ["Boufton Noir", "Amakna, Astrub, Tainéla"],
        ["Tofu Maléfique",   "Cimetières"],
        ["Arakne Malade",    "Souterrains d'Astrub"],
        ["Piou Bleu",    "Astrub, Bonta, Sufokia"],
        ["Piou Jaune",   "Astrub, Bonta, Sufokia"],
        ["Piou Rouge",   "Astrub, Bonta, Sufokia"],
        ["Piou Vert",    "Astrub, Bonta, Sufokia"],
        ["Piou Violet",  "Astrub, Bonta, Sufokia"],
        ["Piou Rose",    "Astrub, Bonta, Sufokia"],
        ["Flameche Air", "Plaine des Scarafeuilles, Nids des Kwaks"],
        ["Flameche Eau", "Plaine des Scarafeuilles, Nids des Kwaks"],
        ["Flameche Feu", "Plaine des Scarafeuilles, Nids des Kwaks"],
        ["Flameche Terre",   "Plaine des Scarafeuilles, Nids des Kwaks"],
        ["Larve Bleue",  "Un peu partout"],
        ["Crabe",    "Zone du Port de Madrestam, Rivages de Sufokia"],
        ["Tofu", "Amakna, Astrub"],
    ],
    [
        ["Tofu Malade",  "Souterrains d'astrub"],
        ["Champ Champ",  "Amakna, Astrub, Champs de Cania, Tainéla"],
        ["Pissenlit Diabolique", "Amakna, Astrub, Champs de Cania, Tainéla"],
        ["Arakne Agressive", "Foret des Abraknydes , Amakna"],
        ["Bandit Manchot",   "Astrub, Passage vers Brâkmar"],
        ["Rose Démoniaque",  "Amakna, Astrub, Champs de Cania, Tainéla"],
        ["Gelée Bleue",  "Péninsule des Gelées, Gelaxième dimension"],
        ["Gelée Menthe", "Péninsule des Gelées, Gelaxième dimension"],
        ["Kwoan",    "Cimetière d'Amakna"],
        ["Larve Verte",  "Un peu partout"],
        ["Bouftou",  "Amakna, Astrub, Tainéla"],
        ["Kolérat",  "Lande de Sidimote"],
        ["Larve Orange", "Un peu partout"],
        ["Boulanger Sombre", "Façade de Brakmâr, Territoire des Bandits"],
        ["Black Tiwabbit",   "Île des Wabbits"],
        ["Tiwabbit", "Île des Wabbits"],
        ["Tiwabbit Kiafin",  "Île des Wabbits"],
        ["Tournesol Sauvage",    "Amakna, Astrub, Champs de Cania"],
        ["Bandit du clan des Roublards", "Territoire des Bandits"],
        ["Gobelin",  "Campement des Bworks, Village dévasté de Gisgoul"],
    ],
    [
        ["NodKoko",  "île de Moon"],
        ["Tikokoko", "île de Moon"],
        ["Trukikol", "île de Moon"],
        ["Sanglier", "Amakna, Astrub"],
        ["Champa Vert",  "Clairière de Brouce Boulgoure, Amakna, Forêt des Abraknydes"],
        ["Citwouille",   "Forêt maléfique"],
        ["Vampire",  "Cimetières de Bonta et Brakmâr, Cryptes"],
        ["Biblop Coco",  "Prairie des Blops, Plaine de Cania"],
        ["Biblop Griotte",   "Prairie des Blops, Plaine de Cania"],
        ["Biblop Indigo",    "Prairie des Blops, Plaine de Cania"],
        ["Biblop Reinette",  "Prairie des Blops, Plaine de Cania"],
        ["Chevaucheur de Karne", "Campement des Bworks, Amakna"],
        ["Milirat d'Egoutant malade",    "Souterrains d'Astrub"],
        ["Boo",  "Coin des Boos, Marécages"],
        ["Prespic",  "Amakna, Astrub"],
        ["Cochon de Lait",   "Presqu'île des Porcos"],
        ["Tortue Jaune", "île de Moon"],
        ["Wabbit",   "île des Wabbits"],
        ["Chef de Guerre Bouftou",   "Amakna, Astrub"],
        ["Berger Porkass",   "Territoire des Porkass, Plaine de Cania"],
    ],
    [
        ["Croc Gland",   "Lande de Sidimote"],
        ["Bulbambou",    "Pandala"],
        ["Tortue Bleue", "île de Moon"],
        ["Tortue rouge", "île de Moon"],
        ["Tortue Verte", "île de Moon"],
        ["Corbac",   "Pénates des Corbac, Lande de Sidimote, Plaine de Cania"],
        ["Etoile de la Mer d'Asse",  "Donjon Ensablé, Calanques d'Astrub, Plage de Cania"],
        ["Pichon Blanc", "Donjon Ensablé, Calanques d'Astrub, Plage de Cania"],
        ["Pichon Bleu",  "Donjon Ensablé, Calanques d'Astrub, Plage de Cania"],
        ["Pichon Orange",    "Donjon Ensablé, Calanques d'Astrub, Plage de Cania"],
        ["Pichon Vert",  "Donjon Ensablé, Calanques d'Astrub, Plage de Cania"],
        ["Bambouto", "Pandala"],
        ["Maître Vampire",   "Cimetières de Bonta et Brakmâr, Cryptes"],
        ["Minoskito",    "île du Minotoror"],
        ["Noeul",    "Labyrinthe du DV"],
        ["Milimulou",    "Amakna, Bois de Litneg"],
        ["Fourbasse",    "île de Moon"],
        ["Bulbiflore",   "Pandala"],
        ["Bwork Mage",   "Campement des Bworks"],
        ["Croc Gland enragé",    "Lande de Sidimote"],
    ],
    [
        ["Rose Obscure", "Champs des Ingalsses"],
        ["Black Wabbit", "île des Wabbits"],
        ["Mineur Sombre",    "Façade de Brakmâr, Territoire des Bandits"],
        ["Bwork Archer", "Campement des Bworks"],
        ["Champa Bleu",  "Clairière des Bruce Boulgour, Forêt des Abraknydes"],
        ["Champa Marron",    "Clairière des Bruce Boulgour, Forêt des Abraknydes"],
        ["Champa Rouge", "Clairière des Bruce Boulgour, Forêt des Abraknydes"],
        ["Craqueboule",  "Astrub, Amakna"],
        ["Mandrine", "île du Minotoror"],
        ["Kitsou Nakwa", "Pandala"],
        ["Gargrouille",  "Le champs du Repos"],
        ["Dragodinde Amande Sauvage",    "Montagne des koalaks"],
        ["Gelée Fraise", "Péninsule des Gelées"],
        ["Wabbit Squelette", "île des Wabbits > île du nord-ouest"],
        ["Chafer Invisible", "Cimetières"],
        ["Craqueleur",   "Amakna"],
        ["Bwork",    "Campement des Bworks"],
        ["Abraknyde",    "Forêt des Abraknydes, Tainéla, Amakna"],
        ["Kraméléhon",   "île du Minotoror"],
    ],
    [
        ["Scarafeuille Blanc",   "Plaine des scarafeuilles"],
        ["Scarafeuille Bleu",    "Plaine des scarafeuilles"],
        ["Scarafeuille Rouge",   "Plaine des scarafeuilles"],
        ["Scarafeuille Vert",    "Plaine des scarafeuilles"],
        ["Rib",  "Cimetière d'Amakna"],
        ["Blop Coco",    "Plairie des Blops, Plaine de Cania"],
        ["Blop Griotte", "Plairie des Blops, Plaine de Cania"],
        ["Blop Indigo",  "Plairie des Blops, Plaine de Cania"],
        ["Blop Reinette",    "Plairie des Blops, Plaine de Cania"],
        ["Cochon de Farle",  "Labyrinthe et Donjon du Dragon Cochon"],
        ["Scaratos", "île du Minotoror"],
        ["Boomba",   "la jungle de Moon"],
        ["Tronknyde",    "Forêt des Abraknydes/sombres"],
        ["Chafer Fantassin", "Cimetière d'Amakna"],
        ["Pichon Kloune",    "Donjon Ensablé, Plage de Cania, Calanques d'Astrub"],
        ["Abrakne",  "Forêt des Abraknydes/sombres"],
        ["Chafer",   "Cimetières"],
        ["Crocodaille",  "Marécages"],
        ["Rat d'Egoutant malade",    "Souterrains profonds d'Astrub"],
        ["Scorbute", "Lande de Sidimote"],
    ],
    [
        ["Dragodinde Rousse Sauvage",    "Territoire des Dragodindes, montagne des Koalaks"],
        ["Forgeron Sombre",  "Façade de Brâkmar, Territoire des Bandits"],
        ["Crustorail Kouraçao",  "Plage de Corail"],
        ["Crustorail Malibout",  "Plage de Corail"],
        ["Crustorail Morito",    "Plage de Corail"],
        ["Crustorail Passaoh",   "Plage de Corail"],
        ["Bulbuisson",   "Pandala"],
        ["Arakne Majeure",   "Egoûts de Bonta et Brâkmar, Forêt des Abraknydes"],
        ["Araknawa", "Pandala"],
        ["Grand Pa Wabbit",  "île des Wabbits"],
        ["Wo Wabbit",    "île des Wabbits"],
        ["Cavalier Porkass", "Plaine des Porkass"],
        ["Aboub",    "Territoire des Dopeuls"],
        ["Amlub",    "Territoire des Dopeuls"],
        ["Codem",    "Territoire des Dopeuls"],
        ["Gink", "Territoire des Dopeuls"],
        ["Kirevam",  "Territoire des Dopeuls"],
        ["Let Emoliug",  "Territoire des Dopeuls"],
        ["Nebgib",   "Territoire des Dopeuls"],
        ["Nipul",    "Territoire des Dopeuls"],
    ],
    [
        ["Osurc",    "Territoire des Dopeuls"],
        ["Susej",    "Territoire des Dopeuls"],
        ["Kokoko",   "Plage de Moon"],
        ["Chafer Archer",    "Cimetière d'Amakna, Cimetière de Bonta et de Brâkmar"],
        ["Chafer Lancier",   "Cimetière d'Amakna, Cimetière de Bonta et de Brâkmar"],
        ["DoK Alako",    "Canyon Sauvage et Lacs Enchantés"],
        ["Koalak Immature",  "Forêt de Kaliptus et Lacs enchantés"],
        ["Gamino",   "Labyrinthe du Minotoror"],
        ["Chaman d'Egoutant",    "Egoûts de Bonta et de Brâkmar, Souterrains d'Astrub"],
        ["Le Ouassingue Entourbé",   "Tourbière d'Otomai, Champ du repos"],
        ["La Ouassingue",    "Tourbière d'Otomai, Champ du repos"],
        ["Le Ouassingue",    "Tourbière d'Otomai, Champ du repos"],
        ["Palmifleur Malibout",  "Plage de Corail"],
        ["Palmifleur Morito",    "Plage de Corail"],
        ["Palmifleur Passaoh",   "Plage de Corail"],
        ["Sanglier Des Plaines", "Forêt de Cania"],
        ["Abraknyde Vénérable",  "Forêt des Abraknydes"],
        ["Craqueleur des plaines",   "Massifs de Cania"],
        ["Pandit",   "Pandala"],
        ["Chafer d'élite",   "Cimetières de Bonta et Brâkmar"],
    ],
    [
        ["Maître Bolet", "Champs de Cania"],
        ["Craqueboule Poli", "Plaines herbeuses"],
        ["Pandikaze",    "Pandala"],
        ["Kanniboul Archer", "Jungle profonde de Moon"],
        ["Kanniboul Jav",    "Jungle profonde de Moon"],
        ["Kanniboul Sarbak", "Jungle profonde de Moon"],
        ["Kanniboul Thierry",    "Jungle profonde de Moon"],
        ["Pandalette Ivre",  "Pandala"],
        ["Rat d'Egoutant",   "Egoûts de Bonta et de Brâkmar, Souterrains d'Astrub"],
        ["Palmifleur Kouraçao",  "Plage de Corail"],
        ["Ouginak",  "Lande de Sidimote"],
        ["DragOeuf Blanc immature",  "Presqu'île des Dragoeufs"],
        ["DragOeuf Doré immature",   "Presqu'île des Dragoeufs"],
        ["DragOeuf Noir immature",   "Presqu'île des Dragoeufs"],
        ["DragOeuf de saphir immature",  "Presqu'île des Dragoeufs"],
        ["Dragoss Blanc",    "Sanctuaire des Dragoeufs"],
        ["Dragoss Doré", "Sanctuaire des Dragoeufs"],
        ["Dragoss Noir", "Sanctuaire des Dragoeufs"],
        ["Dragoss de saphir",    "Sanctuaire des Dragoeufs"],
        ["Léopardo", "Feudala"],
    ],
    [
        ["Serpiplume",   "Labyrinthe du Minotoror"],
        ["Corailleur",   "Plage de Corail"],
        ["Kitsou Nae",   "Pandala"],
        ["Raul Mops",    "Baie de Cania"],
        ["Pandawa Ivre", "Pandala"],
        ["Cooleuvre",    "Pandala"],
        ["Coquille Explosive",   "Presqu'île des Dragoeufs"],
        ["Canon Dorf",   "Bâteau du Chouque, donjon de l'Arche d'Otomai"],
        ["Nakunbra", "Bâteau du Chouque, donjon de l'Arche d'Otomai"],
        ["Don Duss Ang", "Labyrinthe du Dragon Cochon"],
        ["DragOeuf Blanc",   "Presqu'île des Dragoeufs"],
        ["DragOeuf Doré",    "Presqu'île des Dragoeufs"],
        ["DragOeuf Noir",    "Presqu'île des Dragoeufs"],
        ["DragOeuf de saphir",   "Presqu'île des Dragoeufs"],
        ["Koalak Coco",  "Canyon Sauvage"],
        ["Koalak Griotte",   "Canyon Sauvage"],
        ["Koalak Indigo",    "Canyon Sauvage"],
        ["Koalak Reinette",  "Canyon Sauvage"],
        ["Rat d'Hyoactif",   "Egoûts de Bonta et de Brâkmar"],
        ["Sparo",    "Arche d'Otomai"],
    ],
    [
        ["Chiendent",    "Jungle Obcure"],
        ["Fantôme Apero",    "Cimetière de Brâkmar"],
        ["Fantôme Ardent",   "Cimetière de Brâkmar"],
        ["Fantôme Arepo",    "Cimetière de Brâkmar"],
        ["Fantôme Brave",    "Cimetière de Brâkmar"],
        ["Don Dorgan",   "Labyrinthe du Dragon Cochon"],
        ["Barbroussa",   "Arche d'Otomai"],
        ["Le Flib",  "Arche d'Otomai"],
        ["Nerbe",    "Jungle Obscure"],
        ["Chef Crocodaile",  "Les marais"],
        ["Serpentin",    "Plaines de Cania"],
        ["Kanigrou", "Plaines de Cania"],
        ["Bitouf des plaines",   "Plaines herbeuses"],
        ["Craqueleur poli",  "Plaines herbeuses"],
        ["Mufafah",  "Plaines herbeuses"],
        ["Mulou",    "Bois de Litneg"],
        ["Pandule",  "Pandala"],
        ["Kido", "Plaines herbeuses"],
        ["Kilibriss",    "Plaines herbeuses"],
        ["Dragoeuf blanc éveillé",   "Presqu'île des Dragoeufs"],
    ],
    [
        ["Dragoeuf doré éveillé",    "Presqu'île des Dragoeufs"],
        ["Dragoeuf noir éveillé",    "Presqu'île des Dragoeufs"],
        ["Dragoeuf de saphir éveillé",   "Presqu'île des Dragoeufs"],
        ["Dragueuse",    "Sanctuaire des Dragoeufs"],
        ["Guerrier koalak",  "Vallée de la Morh'Kitu"],
        ["Braconnier",   "Pandala"],
        ["Oni",  "Forêt maléfique"],
        ["Warko marron", "Forêt de Kaliptus, Canyon Sauvage"],
        ["Kitsou nere",  "Pandala"],
        ["Abraknyde sombre", "Forêt des Abraknydes sombres"],
        ["Bulbig",   "Pandala"],
        ["Fossoyeur koalak", "Cimetière primitif"],
        ["Koalak forestier", "Forêt de Kaliptus"],
        ["Piralak",  "Lacs enchantés"],
        ["Pékeualak",    "Lacs enchantés"],
        ["Gloutovore",   "Jungle profonde de Moon"],
        ["Abrakne sombre",   "Forêt des Abraknydes sombres"],
        ["Dragodinde dorée sauvage", "Territoire des Dragodindes"],
        ["Chevaucheur koalak",   "Cimetière primitif"],
        ["Meupette", "Arbre Hakam"],
    ],
    [
        ["Bambouto sacré",   "Pandala"],
        ["Dragoeuf guerrier",    "Pandala"],
        ["Dragoeuf volant",  "Sanctuaire des Dragoeufs"],
        ["Aerohouctor le guerrier",  "Souterrains de la presqu'île des Dragoeufs"],
        ["Aquabralak le guerrier",   "Souterrains de la presqu'île des Dragoeufs"],
        ["Ignelicrobur le guerrier", "Souterrains de la presqu'île des Dragoeufs"],
        ["Terrakoubiak le guerrier", "Souterrains de la presqu'île des Dragoeufs"],
        ["Disciple zoth",    "Village des Zoths"],
        ["Brouture", "Jungle obscure d'Otomai"],
        ["Koalak sanguin",   "Vallée de la Morh'Kitu"],
        ["Bitouf sombre",    "Jungle obscure d'Otomai"],
        ["Floribonde",   "Jungle obscure d'Otomai"],
        ["Fécorce",  "Jungle obscure d'Otomai"],
        ["Koalak farouche",  "Vallée de la Morh'Kitu"],
        ["Mama koalak",  "Canyon Sauvage"],
        ["Momie koalak", "Cimetière primitif"],
        ["Bourbassingue",    "Tourbière d'Otomai"],
        ["Warko violet", "Vallée de la Morh'Kitu"],
        ["Gamine zoth",  "Village des Zoths"],
        ["Guerrier zoth",    "Village des Zoths"],
    ],
    [
        ["Tourbassingue",    "Tourbière d'Otomai"],
        ["Abrakleur sombre", "Jungle Obscure d'Otomai"],
        ["Dragoss blanc éveilé", "Sanctuaire des Dragoeufs"],
        ["Dragoss doré éveillé", "Sanctuaire des Dragoeufs"],
        ["Dragoss noir éveillé", "Sanctuaire des Dragoeufs"],
        ["Dragoss de saphir éveillé",    "Sanctuaire des Dragoeufs"],
        ["Soryo firefoux",   "Feudala"],
        ["Kitsou nufeu", "Pandala"],
        ["Maho firefoux",    "Feudala"],
        ["Drakoalak",    "Canyon Sauvage"],
        ["Fauchalak",    "Vallée de la Morh'Kitu"],
        ["Maître koalak",    "Cimetière Primitif"],
        ["Poolay",   "Arbre Hakam"],
        ["Ignerkocropos l'affamé",   "Sanctuaire des Dragoeufs"],
        ["Terraburkal le perfide",   "Sanctuaire des Dragoeufs"],
        ["Aqualikros l'impitoyable", "Sanctuaire des Dragoeufs"],
        ["Aerotrugobur le malveillant",  "Sanctuaire des Dragoeufs"],
        ["Trooll",   "Bois de Litneg"],
    ],
    [
        ["Sergent zoth", "Village des Zoths"],
        ["maître zoth",  "Village des Zoths"],
        ["kKaskargo",    "Arbre Hakam"],
        ["Bitouf aérien",    "Arbre Hakam"],
        ["Abrakleur clair",  "Arbre Hakam"],
        ["Yokai firefoux",   "Pandala Feu"],
        ["Champaknyde",  "Cave des Fungus"],
        ["Tromperelle",  "Cave des Fungus"],
        ["Champodonte",  "Cave des Fungus"],
        ["Champbis", "Cave des Fungus"],
        ["Champ à gnon", "Cave des Fungus"],
        ["Champmane",    "Cave des Fungus"],
        ["Fantôme léopardo", "île de Grobe"],
        ["Fantôme pandikaze",    "île de Grobe"],
        ["Fantôme pandule",  "île de Grobe"],
        ["Fantôme soryo",    "île de Grobe"],
        ["Pandore",  "Pandala"],
        ["Roissingue",   "Tourbière"],
        ["Fantôme maho", "île de Grobe"],
        ["Fantôme yokai",    "île de Grobe"],
    ],
    [
        ["Fantôme pandore",  "île de Grobe"],
        ["Fantôme Tanukouï San", "île de Grobe"]
    ],
    [
        ["Mob l'Eponge",    "Donjon"],
        ["Bouftou Royal",   "Donjon"],
        ["Tournesol Affamé",    "Donjon"],
        ["Gelée Royale Bleue",  "Donjon"],
        ["Gelée Royale Menthe", "Donjon"],
        ["Shin Larve",  "Donjon"],
        ["Wabbit GM",   "Donjon"],
        ["Scarabosse Doré", "Donjon"],
        ["Bworkette",   "Donjon"],
        ["Dragon Cochon",   "Donjon"],
        ["Mominotor",   "Donjon"],
        ["Déminoboule", "Donjon"],
        ["Tofu Royal",  "Donjon"],
        ["Blop Coco Royal", "Donjon"],
        ["Blop Griotte Royal",  "Donjon"],
        ["Blop Indigo Royal",   "Donjon"],
        ["Blop Reinette Royal", "Donjon"],
        ["Rat Noir",    "Donjon"],
        ["Rat Blanc",   "Donjon"],
        ["Minotoror",   "Donjon"],
    ],
    [
        ["Dark vlad",   "Donjon"],
        ["Tanukoui San",    "Donjon"],
        ["Craqueleur légendaire",   "Donjon"],
        ["Gardienne des égouts",    "Donjon"],
        ["Gelée royale fraise", "Donjon"],
        ["Maître corbac",   "Donjon"],
        ["Blop multicolore royal",  "Donjon"],
        ["Corailleur magistral",    "Donjon"],
        ["Gourlo le terrible",  "Donjon"],
        ["Meulou",  "Donjon"],
        ["Wa wabbit",   "Donjon"],
        ["Moon",    "Donjon"],
        ["Koulosse",    "Donjon"],
        ["Skeunk",  "Donjon"],
        ["Abraknyde ancestral", "Donjon"],
        ["Maître pandore",  "Donjon"],
        ["Tynrils (4)", "Donjon"],
    ],
    [
        ["Gelée royale citron", "Donjon"],
        ["Touchparak",  "Donjon"],
        ["Bworker", "Donjon"],
        ["Sphincter cell",  "Donjon"],
        ["Minotot", "Donjon"],
        ["Silf le rasboul majeur",  "Donjon"],
        ["Crocabulia",  "Donjon"],
        ["Péki péki",   "Donjon"],
        ["Chêne mou",   "Donjon"],
        ["Ougah",   "Donjon"],
        ["Kimbo",   "Donjon"],
    ],
    [
        ["Sourizoto le Collant","Souris Grise"],
        ["Mosketère le Dévoué","Moskito"],
        ["Arakule la Revancharde","Arakne"],
        ["Boudalf le Blanc","Boufton Blanc"],
        ["Boulgouvril le Lointain","Boufton Noir"],
        ["Tofumanchou l'Empereur","Tofu Maléfique"],
        ["Arachitik la Souffreteuse","Arakne Malade"],
        ["Pioustone le Problème","Piou Bleu"],
        ["Pioulbrineur le Mercenaire","Piou Jaune"],
        ["Pioulette la Coquine","Piou Rouge"],
        ["Pioukas la Plante","Piou Vert"],
        ["Pioussokrim le Délétère","Piou Violet"],
        ["Craraboss le Féérique","Crabe"],
        ["Larvonika l'Instrument","Larve Bleue"],
        ["Pioufe la Maquillée","Piou Rose"],
        ["Tofuldebeu l'Explosif","Tofu"],
        ["Tofurapin le Pétri","Tofu Malade"],
        ["Chamchie le Difficile","Champ Champ"],
        ["Pissdane l'Insipide","Pissenlit Diabolique"],
        ["Araknay la Galopante","Arakne Agressive"],
    ],
    [
        ["Bandapar l'exclus","Bandit Manchot"],
        ["Roz la magicienne","Rose Démoniaque"],
        ["Gelanal le Huileux","Gelée Bleue"],
        ["Kwoanneur le Frimeur","Kwoan"],
        ["Larchimaide la poussée","Larve Verte"],
        ["Boufdégou le Refoulant","Bouftou"],
        ["Kolforthe l'Indécollable","Kolérat"],
        ["Geloliaine l'aérien","Gelée Menthe"],
        ["Larvastrès le Subjectif","Larve Orange"],
        ["Serpistol l'Illustre","Serpentin"],
        ["Tiwa'Missou le Gateux","Black Tiwabbit"],
        ["Boudur le raide","Boulanger sombre"],
        ["Tiwalpé le Dévêtu","Tiwabbit"],
        ["Tiowflan le Lâche","Tiwabbit Kiaffin"],
        ["Tour le Vice","Tournesol Sauvage"],
        ["Bandson le Tonitruant","Bandit du Clan des Roublards"],
        ["Gobstinais le Têtu","Gobelin"],
        ["Nodkoku le Trahi","Nodkoko"],
        ["Tikosto le Mousse","Tikoko"],
        ["Trukul le Lent","Trukikol"],
    ],
    [
        ["Sangria le Fruité","Sanglier"],
        ["Champayr le Disjoncté","Champa Vert"],
        ["Citassaté le Service","Citwouille"],
        ["Vampunor le Glacial","Vampire"],
        ["Bilvoezé le Bonimenteur","Biblop Coco"],
        ["Bi le Partageur","Biblop Griotte"],
        ["Bitsou le Quêteur","Biblop Indigo"],
        ["Bitsou le Rieur","Biblop Reinette"],
        ["Chevaustine le Reconstruit","Chevaucheur de Karne"],
        ["Milipussien le Géant","Milirat d'Egoutant Malade"],
        ["Boostif l'Affamé","Boo"],
        ["Preskapwal le Tendancieux","Prespic"],
        ["Chonstip la Passagère","Cochon de Lait"],
        ["Torthur la Lutte","Tortue Jaune"],
        ["Wabbitud le Constant","Wabbit"],
        ["Porfavor le Quémandeur","Berger Porkass"],
        ["Bulleur le Dormeur","Bulbambou"],
        ["Bouflet le Puéril","Chef de guerre bouftou"],
        ["Cromikay le Néophyte","Croc gland"],
        ["Tortenssia la Fleurie","Tortue Bleue"],
    ],
    [
        ["Bambouské le Camouflé","Bambouto"],
        ["Corpat le Vampire","Corbac"],
        ["Pichduite le Totem","Pichon Blanc"],
        ["Pichdourse le Puissant","Pichon bleu"],
        ["Pichtoire l'Erudit","Pichon orange"],
        ["Pichakoté le Dégoûtant","Pichon vert"],
        ["Tortorak le Cornu","Tortue rouge"],
        ["Maître Amboat le Moqueur","Maître Vampire"],
        ["Buldeflore le Pénétrant","Bulbiflore"],
        ["Fourapin le Chaud","Fourbasse"],
        ["Milipatte la Griffe","Milimulou"],
        ["Minoscour le Sauveur","Minoskito"],
        ["Neufedur le Flottant","Noeul"],
        ["Tortilleur le Coulé","Tortue Verte"],
        ["Bworkmage le Respectueux","Bwork Mage"],
        ["Wagnagnah le Sanglant","Black Wabbit"],
        ["Crognan le Barbare","Croc gland enragé"],
        ["Rostensyl la Cuisinière","Rose Obscur"],
        ["Minsinistre l'Elu","Mineur Sombre"],
        ["Barchwork le Multicolore","Bwork Archer"],
    ],
    [
        ["Champayt l'Odorant","Champa Bleu"],
        ["Chamflay le Ballonné","Champa Marron"],
        ["Chamdblé le Cultivé","Champa Rouge"],
        ["Craquetuss le Piquant","Craqueboule"],
        ["Mandalo l'Aqueuse","Mandrine"],
        ["Kitsoupierre le Récipient","Kitsou Nere"],
        ["Garsim le Mort","Gargrouille"],
        ["Draglida la Disparue","Dragodinde Amande"],
        ["Gelaviv le Glaçon","Gelée Rouge"],
        ["Watdogue le Bien Nommé","Wabbit Squelette"],
        ["Chafalfer l'Optimiste","Chafer Invisible"],
        ["Crakmitaine le Faucheur","Craqueleur"],
        ["Bworkasse le Dégoûtant","Bwork"],
        ["Abrakroc l'Edenté","Abraknyde"],
        ["Krapahut le Randonneur","Kraméléhon"],
        ["Scapé l'Epée","Scarafeuille Blanc"],
        ["Scarfaysse le Balafré","Scarafeuille Bleu"],
        ["Scarouarze l'Epopsée","Scarafeuille rouge"],
        ["Scaramel le Fondant","Scarafeuille vert"],
        ["Ribibi le Cher","Rib"],
    ],
    [
        ["Blorie l'Assourdissante","Blop Coco"],
        ["Blordur l'Infect","Blop Griotte"],
        ["Bloporte le Veule","Blop Indigo"],
        ["Blof l'Apathique","Blop Reinette"],
        ["Boombata le Garde","Boomba"],
        ["Farlon l'Enfant","Cochon de farle"],
        ["Scaratyne l'huître","Scaratos"],
        ["Chaffoin le Sournois","Chafer fantassin"],
        ["Picht le Brioché","Pichon kloune"],
        ["Tronkoneuze la Tranchante","Tronknyde"],
        ["Abrakadnuzar","Abrakne"],
        ["Chafemal le Bagarreur","Chafer"],
        ["Crolnareff l'Exilé","Crocodaile"],
        ["Radoutable le Craint","Rat d'Egoutant Malade"],
        ["Scorpitène l'Enflammé","Scorbute"],
        ["Dragnoute l'Irascible","Dragodinde Rousse"],
        ["Bulsavon le Gonflé","Bulbuisson"],
        ["Crustterus l'Organique","Crustorail Kouraçao"],
        ["Crustensyl le Pragmatique","Crustorail Malibout"],
        ["Cruskof le Rustre","Crustorail Morito"],
    ],
    [
        ["Crusmeyer le Pervers","Crustorail Passaoh"],
        ["Forboyar l'Enigmatique","Forgeron Sombre"],
        ["Arakozette l'intrépide","Araknawa"],
        ["Arabord la Cruche","Arakne Majeure"],
        ["Grandilok le Clameur","Grand Pa Wabbit"],
        ["Wokenrol le Danseur","Wo Wabbit"],
        ["Cavordemal le Sorcier","Cavalier Porkass"],
        ["Aboudbra le Porteur","Dopeul Osamodas"],
        ["Ameur la Laide","Dopeul Féca"],
        ["Codenlgaz le Problème","Dopeul Eniripsa"],
        ["Ginsenk le Stimulant","Dopeul Sadida"],
        ["Kiroyal le Sirupeux","Dopeul Ecaflip"],
        ["Let le Rond","Dopeul Cra"],
        ["Nelvin le Boulet","Dopeul Xélor"],
        ["Nipulnislip l'Exibitionniste","Dopeul Sram"],
        ["Osuxion le Vampirique","Dopeul Enutrof"],
        ["Susbewl l'Hypocrite","Dopeul Iop"],
        ["Koktèle le Secoué","Kokoko"],
        ["Chafmarcel le Fêtard","Chafer Archer"],
        ["Chalan le Commerçant","Chafer Lancier"],
    ],
    [
        ["Chamitant le","Dillettante Chaman d'Egoutant"],
        ["Doktopuss le","Maléfique Dok Alako"],
        ["Germinol l'Indigent","Gamino"],
        ["Koalastrof la","Naturelle Koalak immature"],
        ["Ouature la Mobile","La Ouassingue"],
        ["Ouassébo l'Esthète","Le Ouassingue"],
        ["Ouashouah l'Exubérant","Le Ouassingue Entourbé"],
        ["Palmito le Menteur","Palmifleur Malibout"],
        ["Palmiche le Serein","Palmifleur Morito"],
        ["Palmiflette le Convivial","Palmifleur Passaoh"],
        ["Sampi l'Eternel","Sanglier des plaines"],
        ["Abrakildas le Vénérable","Abraknyde Vénérable"],
        ["Cramikaz le Suicidaire","Craqueleur des Plaines"],
        ["Pandimaensh l'Animateur","Pandit"],
        ["Chafrit le Barbare","Chafer d'Elite"],
        ["Craquetou le Fissuré","Craqueboule poli"],
        ["Maître Onom le Régulier","Maître Bolet"],
        ["Pandimy le Contagieux","Pandikaze"],
        ["Kannibal le Lecteur","Kanniboule Archer"],
        ["Kapota la Fraise","Kanniboule Jav"],
    ],
    [
        ["Kannémik le Maigre","Kanniboule Sarbak"],
        ["Kannisterik le Forcené","Kanniboule Thierry"],
        ["Pandanlagl la Saoule","Pandalette Ivre"],
        ["Palmbytch la Bronzée","Palmifleur Kouraçao"],
        ["Ratlbol l'Aigri","Rat d'Egoutant"],
        ["Ougaould le Parasite","Ouginak"],
        ["Corboyard l'Enigmatique","Corailleur"],
        ["Dragstik le Frustre","Dragoeuf Blanc immature"],
        ["Dragtula l'Ancien","Dragoeuf de saphir immature"],
        ["Dragsta le Détendu","Dragoeuf Noir immature"],
        ["Dragstore le Généraliste","Dragoeuf Doré immature"],
        ["Dragtopaile l'Excavateur","Dragoss Blanc"],
        ["Dragioli le Succulent","Dragoss de saphir"],
        ["Dragalgan l'Effervescent","Dragoss Doré"],
        ["Dragybuss le Sucré","Dragoss Noir"],
        ["Léopolnor le Barde","Leopardo"],
        ["Serpistule le Purulent","Serpiplume"],
        ["Kitsoudbra le Malodorant","Kitsou Nae"],
        ["Pandouille le Titubant","Pandawa Ivre"],
        ["Rauligo le Sale","Raul Mops"],
    ],
    [
        ["Cooligane le Nevrosé","Cooleuvre"],
        ["Caboume l'Artilleur","Canon Dorf"],
        ["Nakuneye le Borgne","Nakumbra"],
        ["Dragstayr le Fonceur","Dragoeuf Blanc"],
        ["Dragmoclaiss le Fataliste","Dragoeuf de saphir"],
        ["Dragkouine la Déguisée","Dragoeuf Doré"],
        ["Dragnostik le Sceptique","Dragoeuf Noir"],
        ["Koamaembair le Coulant","Koalak Coco"],
        ["Koakofrui le Confit","Koalak Griotte"],
        ["Koaskette la Chapelière","Koalak Indigo"],
        ["Koarmit la Batracienne","Koalak Reinette"],
        ["Ratéhaifaim le Professeur","Rat d'hyoactif"],
        ["Sparoket le Lanceur","Sparo"],
        ["Chiendanslémain l'Illusionniste","Chiendent"],
        ["Fanlabiz le Véloce","Fantôme Apero"],
        ["Fandanleuil le Précis","Fantôme Ardent"],
        ["Fantoch le Pantin","Fantôme Arepo"],
        ["Fantrask le Rêveur","Fantôme Brave"],
        ["Barebourd le Comte","Barbroussa"],
        ["Nerdeubeu le Flagellant","Nerbe"],
    ],
    [
        ["Crathdogue le Cruel","Craqueleur Poli"],
        ["Toufou le Benêt","Bitouf des Plaines"],
        ["Crok le Beau Chef","Crocodaile"],
        ["Fanfancisco le Cosmopolite","Fantôme Tanuki Chan air"],
        ["Fanjipann le Sucré Fantôme","Tanuki Chan eau"],
        ["Fanhatur le Simple Fantôme","Tanuki Chan terre"],
        ["Fanjo le Pilote Fantôme","Tanuki Chan feu"],
        ["Fanimyl l'Acuité Fantôme","Tanuki Chan neutre"],
        ["Kanasukr le Mielleux","Kanigrou"],
        ["Mufguedin le Suprême","Mufafah"],
        ["Muloufok l'Hilarant","Mulou"],
        ["Pangraive le Militant","Pandule"],
        ["Kido l'âtre","Kido"],
        ["Kilimanj'haro le Grimpeur","Kilibriss"],
        ["Dragoo le Cramoisi","Dragoeuf Blanc éveillé"],
        ["Dragtonien le Malvoyant","Dragoeuf de saphir éveillé"],
        ["Dragma le Bouillant Dragoeuf","Doré éveillé"],
        ["Dragoeth le Penseur Dragoeuf","Noir éveillé"],
        ["Dragonienne l'Econome","Dragueuse"],
        ["Guerrite le veilleur","Guerrier Koalak"],
    ],
    [
        ["Bramin le Bicéphale","Braconnier"],
        ["Onihylis le Destructeur","Oni"],
        ["Warkolad l'Etreinte","Warko Marron"],
        ["Kitsoupopulère le Généreux","Kitsou Nere"],
        ["Abrakanette l'Encapsulé","Abraknyde sombre"],
        ["Bulgig le Danseur","Bulbig"],
        ["Fossamoel le Juteux Fossoyeur","Koalak"],
        ["Gloubibou le Gars","Gloutovore"],
        ["Koasossyal le Psychopathe","Koalak Forestier"],
        ["Pékeutar le Tireur","Pékeualak"],
        ["Piradain le Pingre","Piralak"],
        ["Abraklette le Fondant","Abrakne Sombre"],
        ["Koamag'oel le Défiguré","Chevaucheur Koalak"],
        ["Meuroup le Prêtre","Meupette"],
        ["Bambono le Divin","Bambouto Sacré"],
        ["Dragdikal le Décisif","Dragoeuf Guerrier"],
        ["Dragobert le Monarque","Dragoeuf Volant"],
        ["Diskord le Belliqueux","Disciple Zoth"],
        ["Brouste l'Humiliant","Brouture"],
        ["Bitoven le Musicien","Bitouf Sombre"],
    ],
    [
        ["Ecorfé la Vive","Fécorce"],
        ["Floanna la Blonde","Floribonde"],
        ["Koalvissie le Chauve","Koalak Sanguin"],
        ["Koalabois le Calorifère","Koalak Farouche"],
        ["Mamakomou l'âge","Mama Koalak"],
        ["Momikonos la Bandelette","Momie Koalak"],
        ["Boulivert le Géant","Bourbassingue"],
        ["Wara l'Amer Warko","Violet"],
        ["Gastroth la Contagieuse","Gamine Zoth"],
        ["Guerumoth le Collant","Guerrier Zoth"],
        ["Tourbiket le Virevoletant","Tourbassingue"],
        ["Abrakine le Sombre","Abrakleur Sombre"],
        ["Dragminster le Magicien","Dragoss Blanc Eveillé"],
        ["Dragtarus le Bellâtre","Dragoss Doré Eveillé"],
        ["Draquetteur le Voleur","Dragoss Noir Eveillé"],
        ["Drageaufol la Joyeuse","Dragoss de saphir Eveillé"],
        ["Soryonara le Poli","Soryo Firefoux"],
        ["Kitsoufre l'Explosif","Kitsou Nufeu"],
        ["Mahoku le Botté","Maho Firefoux"],
        ["Drakolage le Tentateur","Drakoalak"],
    ],
    [
        ["Faufoll la Joyeuse","Fauchalak"],
        ["Maître Koantik le Théoricien","Maître Koalak"],
        ["Poolopo la Traditionnelle","Poolay"],
        ["Trooyé l'Oxydé","Troll"],
        ["Seripoth l'Ennemi","Sergent Zoth"],
        ["Kaskapointhe la Couverte","Kaskargo"],
        ["Toutouf le Velu","Bitouf Aérien"],
        ["Abrinos le Clair","Abrakleur Clair"],
        ["Don Kizoth l'Obstiné","Maître Zoth"],
        ["Chamiléro le Malchanceux","Champaknyde"],
        ["YokaiKoral le Duel","Yokai Firefoux"],
        ["Tromplamor le Survivant","Tromperelle"],
        ["Chamoute le Duveteux","Champodonte"],
        ["Fansissla l'âne","Fantôme Léopardo"],
        ["Fanstatik l'Etonnant","Fantôme Pandikaze"],
        ["Champoul l'Illuminé","Champbis"],
        ["Champolyon le Polyglotte","Champ à Gnons"],
        ["Champmé le Méchant","Champmane"],
        ["Fandouich l'Hautain","Fantôme Pandule"],
        ["Fanhopruno le Gourmet","Fantôme Soryo"],
    ],
    [
        ["Pandive le végétarien","Pandore"],
        ["Roy le Merlin","Roissingue"],
        ["Fanlagoel le Comique","Fantôme Maho"],
        ["Fantassein le Soldat","Fantôme Yokai"],
        ["Fanburn le Viril","Fantôme Tanukoui San"],
        ["Fanssiss la Brêle","Fantôme Pandore"],
    ],
    [
        ["Le Kralamoure Géant", "Donjon de la tourbière"]
    ]
];