import DS from 'ember-data';

export default DS.Model.extend({
    userId: DS.attr('string'),
    target: DS.attr('number'),

    step1: DS.attr('string'),
    step2: DS.attr('string'),
    step3: DS.attr('string'),
    step4: DS.attr('string'),
    step5: DS.attr('string'),
    step6: DS.attr('string'),
    step7: DS.attr('string'),
    step8: DS.attr('string'),
    step9: DS.attr('string'),
    step10: DS.attr('string'),
    step11: DS.attr('string'),
    step12: DS.attr('string'),
    step13: DS.attr('string'),
    step14: DS.attr('string'),
    step15: DS.attr('string'),
    step16: DS.attr('string'),
    step17: DS.attr('string'),
    step18: DS.attr('string'),
    step19: DS.attr('string'),
    step20: DS.attr('string'),
    step21: DS.attr('string'),
    step22: DS.attr('string'),
    step23: DS.attr('string'),
    step24: DS.attr('string'),
    step25: DS.attr('string'),
    step26: DS.attr('string'),
    step27: DS.attr('string'),
    step28: DS.attr('string'),
    step29: DS.attr('string'),
    step30: DS.attr('string'),
    step31: DS.attr('string'),
    step32: DS.attr('string'),
    step33: DS.attr('string'),
    step34: DS.attr('string'),
    step35: DS.attr('string')
});
